add option to allow jwk.ParseKey to require public or private key types
lestrrat-go/jwx pull request #994
Opened 2023-10-13 06:16 UTC by sding3

This PR adds a new `ParseOption` `WithPrivateKey(bool)` to allow the caller to impose one additional validation criteria to 
`jwk.ParseKey` for symmetric key types, and this validation criteria is to check check if the symmetric key being parsed is a private key or a public key. This affords an easy means for consumers who wish to validate their assumptions about symmetric key being public or private.

I see that there are other functions, such as `jwk.Parse`, that are supposed to handle `ParseOption` too, so I'll implement the handling in those places as well as add unit tests after I can get some initial feedback regarding whether this is something we want to even do at all.

cc: @lestrrat

2023-10-13 06:33 UTC, lestrrat commented
@sding3 Thank you for your PR.

So, the idea is that for a given asymmetric key, have jwx check if it's private?

```go
if _, err := jwk.ParseKey( jsondata, jwk.WithPrivate(true); err != nil {
   return fmt.Errorf(`key must be private key: %w`, err)
}
```

My initial gut reaction is that it doesn't belong in jwx -- if the RFCs **do** allow symmetric keys, I don't think it's a good idea to allow options that can't be use for all key types in the main entry point of the API.

I'd be more comfortable with something like

```go
package jwk

type isPrivater interface{ // BAD name...
   IsPrivate() bool
} 
func IsPrivateKey(key Key) bool {
  ip, ok := key.(isPrivater)
  if ok {
     return ip.IsPrivate()
  }
  return false
}
```

... and add a `IsPrivate()`   method to the keys, so you can do

```go
key, err := jwk.ParseKey(...)
if key.KeyType() != jwa.OctetSeq {
  if !jwk.IsPrivate(key) {
     return fmt.Errorf(`key must be private (was: %T)`, key)
  }
}
```

Anyway, that's my initial reaction, but please feel free to convince me otherwise.

2023-10-13 07:15 UTC, sding3 commented
Thank you for the feedback! Agreed that separating this off into its own function makes more sense. I've pushed the update. Only deviation from your suggestion is that I have `IsPrivate` to be able to return an error upon encountering a non-asymmetric key.

2023-10-13 07:38 UTC, lestrrat requested changes
I added a few comments. If you want, I can fix up the PR for you, but some people don't like that, so... :) just let me know either way.

2023-10-13 07:38 UTC, lestrrat commented on jwk/jwk.go
> +
We're planning to make it possible for third parties to add their new key types, so I think this interface should be public, allowing new keys to decide for themselves if they want to opt-in to this mechanism.

How about

```go
package jwk

type AsymmetricKey interface {
   IsPrivate() (bool, error)
}
```

2023-10-13 07:38 UTC, lestrrat commented on jwk/jwk.go
> +	ak, ok := k.(asymmetricKey)
I think this check can just be

```go
symmetric, ok := k.(SymmetricKey)
if ok {
   return symmetric.IsPrivate(), nil
}
```

2023-10-13 07:38 UTC, lestrrat commented on jwk/jwk.go
> +func IsPrivate(k Key) (bool, error) {
```suggestion
func IsPrivateKey(k Key) (bool, error) {
```

I think that this feels more natural:

```go
key.IsPrivate()
jwk.IsPrivateKey(key)
```

2023-10-13 07:38 UTC, lestrrat commented on jwk/jwk_internal_test.go
> +func TestIsPrivate(t *testing.T) {
This internal test thing is going to go away, so I'd like to refrain from adding tests in this file. Can you please test through the public API. Yeah, I know it's a bit of a pain, but I'm sure you can find source for all of the key types throughout the test

2023-10-14 03:21 UTC, sding3 commented
Thanks for the review. I think I've hit all the comments:

- exported jwk.AsymmetricKey interface
- renamed jwk.IsPrivate to jwk.IsPrivateKey
- moved units out of jwk_internal_test.go

2023-10-14 03:49 UTC, lestrrat commented
Thanks. LGTM! but please be aware that I won't be making a release immediately afterwards, just to make sure that nothing unintended happens because of this change. Please use specify the appropriate SHA1 from go.mod. And when/if you reach a point where you MUST have a released version and we haven't yet done so, please ping us then.

2023-10-14 03:49 UTC, merged